### ISSUE TITLE
Weight file error ?

### ISSUE THREAD

**Issue by Hasanmog** [ZhanYang-nwpu/RSVG-pytorch#14]
Firstly, good job!
I was testing your model on the RSVGD dataset, but got the following problem when loading the weight file.

`!python RSVG-pytorch/main.py --images_path "/content/drive/MyDrive/JPEGImages" --anno_path "/content/drive/MyDrive/Annotations" --pretrain "/content/drive/MyDrive/detr-r50-e632da11.pth" --test`
```
`pretrained_dict = checkpoint['state_dict']

KeyError: 'state_dict'`
```
According to what I searched about the cause of this error , it is  either the weight file is corrupted or missing parameters.
Any Idea ?

**Comment by aghand0ur** [comment]
The authors only provided the pre-trained weights.
However, the resultant trained model checkpoints are not available.

Any plan to release them soon @ZhanYang-nwpu?
