### ISSUE TITLE
image compression broken

### ISSUE THREAD

**Issue by peiwang062** [ZhanYang-nwpu/RSVG-pytorch#7]
Hi, when I try to unzip the image compression, it has an error, 'please check that you have transferred or created the zipfile in the appropriate BINARY mode and that you have compiled UnZip properly'.

I tried on multiple device. The same error occurred.

Any idea about this?

**Comment by AlvinChe** [comment]
met 'image compression broken' problem today. my laptop is macbook pro and i solved this problem by [this](https://blog.csdn.net/abracadabraa/article/details/124928179)

**Comment by peiwang062** [comment]
Thanks everyone! It worked when I used a window pc.
